labelPRBasedOnFilePath:
  cicd:
    - .github/workflows/**
  project-config:
    - .github/settings.yml
  chore:
    - .github/**
  documentations:
    - documentation/**
    - mkdocs.yml
    - .github/ISSUE_TEMPLATE/**
    - .github/pull_request_template.md
